Scmod 6890 new
WorkerFramework/worker-framework pull request #105
Opened 2020-04-27 14:10 UTC by thilagasanthosh

http://sou-jenkins2.swinfra.net/job/WorkerFramework/job/WorkerFramework~worker-framework~SCMOD-6890-New~CI/

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/WorkerFramework_CI_worker-framework_SCMOD-6890-New/

![SEPG_QA_docs](https://user-images.githubusercontent.com/5318352/80381506-efee4d80-8898-11ea-906c-e12588ebbd1a.PNG)

@dermot-hardy ,
Only the first 4 team members or fist <hr> are getting displayed on the documentation page. I am looking into the issue for remaining <hr>. Meanwhile, I have created draft PR for the change.

2020-04-27 18:23 UTC, dermot-hardy requested changes
I don't understand your comments.  Also I only see Andy and Anthony on the Docs QA page:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/WorkerFramework_CI_worker-framework_SCMOD-6890-New/pages/en-us/Team

2020-04-28 12:13 UTC, thilagasanthosh commented
@dermot-hardy ,
Now the doc site team page issue is fixed.
There is some issue due no space between url: and host name in the github url.

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/WorkerFramework_CI_worker-framework_SCMOD-6890-New/pages/en-us/Team

2020-04-28 12:14 UTC, thilagasanthosh commented
Andy asked to do the change in Gemfile as per the doc
https://help.github.com/en/enterprise/2.14/user/articles/setting-up-your-github-pages-site-locally-with-jekyll

2020-04-28 12:21 UTC, dermot-hardy approved these changes

2020-04-28 12:25 UTC, merged