CAF-2005: Implement delete for store-fs
WorkerFramework/worker-framework pull request #19
Opened 2017-01-05 18:33 UTC by aaronoloughlin

2017-01-06 09:34 UTC, andyreidz requested changes
Use store-cs as a guide.

Track the number of delete requests.
https://github.com/WorkerFramework/worker-framework/blob/develop/worker-store-cs/src/main/java/com/hpe/caf/worker/datastore/cs/StorageServiceDataStore.java#L65

And report them.

Where are tests?

2017-01-06 17:04 UTC, aaronoloughlin commented
Amended files according to @andyreidz requested changes.

2017-01-10 14:25 UTC, pcrookshpe submitted a review, later dismissed

2017-01-10 14:25 UTC, pcrookshpe commented on worker-store-fs/src/main/java/com/hpe/caf/worker/datastore/fs/FileSystemDataStore.java
> +            throw new DataStoreException("Failed to delete reference", e);
The exception message could include the reference.

2017-01-10 15:20 UTC, andyreidz approved these changes

2017-01-10 15:51 UTC, merged