CAF-1759: Error Handling Guidance Documentation Update
WorkerFramework/worker-framework pull request #2
Opened 2016-11-28 15:42 UTC by zaramckeown

2016-11-29 14:08 UTC, glucy requested changes
Reviewed.  Please answer or fix before merging can be completed.

2016-11-29 14:08 UTC, glucy commented on worker-framework/docs/pages/en-us/Architecture.md
>  ### Data Store
Are we not adding in the section of Poison Messages here?

2016-11-29 14:08 UTC, glucy commented on worker-framework/docs/pages/en-us/Features.md
>      subtitle: Analyze a Larger Range of Formats
Has the documentation be re-built and re-published?  
  
This comment applies to all the document site content files.

2016-11-29 19:24 UTC, zaramckeown commented on worker-framework/docs/pages/en-us/Features.md
>      subtitle: Analyze a Larger Range of Formats
I was going to do this once the review had been completed. Does that sound okay?

2016-11-29 19:25 UTC, zaramckeown commented
Added Poison Messages to Architecture.md

2016-11-30 09:16 UTC, glucy approved these changes

2016-11-30 09:16 UTC, merged