CAF-2946: Adding hash-on-store methods to DataStore.
WorkerFramework/worker-framework pull request #46
Opened 2017-05-22 15:12 UTC by pcrookshpe

The surprisingly awkward code in hashStore(InputStream,...) is an attempt to hash the stream while it is being read for storing.

2017-05-22 15:50 UTC, pcrookshpe commented
The JIRA ticket https://jira.autonomy.com/browse/CAF-2946 says to extend DataStore but that meant adding default methods to avoid breaking existing implementations of the interface, resulting in the DataStore interface getting more complex than we might have realised when story-pointing the ticket. Let me know if this is acceptable...

2017-05-23 15:39 UTC, kploch requested changes

2017-05-23 15:39 UTC, kploch commented on worker-api/src/main/java/com/hpe/caf/api/worker/HashStoreResult.java
> +    public void setReference(final String reference)
I don't think you need setters on this type. And you can make the reference and hash final keeping this type immutable.

2017-05-24 09:02 UTC, dermot-hardy requested changes
Looking at the size of this change, and especially the fact that it has required two extra dependecies to be added to worker-api, which is essentially meant to be an interface-only module, I think we need to move this logic out into another utility module, util-store perhaps.

One utility method would do - we don't really need the byte[] or Path versions.

2017-05-24 09:13 UTC, dermot-hardy requested changes
As discussed, try using a `HashingInputStream` instead.  I would expect it to be much simpler.

2017-05-24 17:02 UTC, dermot-hardy requested changes

2017-05-24 17:02 UTC, dermot-hardy commented on util-store/src/main/java/com/hpe/caf/util/store/StoreUtil.java
> +    public static HashStoreResult hashStore(final DataStore dataStore, final Path dataPath, final String partialReference)
This method is reading the file twice.  If it just used the first hashStore() overload that takes a stream it would only be reading the file once.

2017-05-24 17:02 UTC, dermot-hardy commented on worker-store-fs/src/test/java/com/hpe/caf/worker/datastore/fs/FileSystemDataStoreTest.java
> +import com.hpe.caf.api.worker.*;
You should try to avoid the star import.  It is considered bad practice:
http://checkstyle.sourceforge.net/config_imports.html#AvoidStarImport

2017-05-25 10:21 UTC, kploch approved these changes

2017-05-25 10:21 UTC, merged