CAF-2930: Removing worker-store-cs and closed-source
WorkerFramework/worker-framework pull request #53
Opened 2017-06-12 14:58 UTC by arogan92

* Removed storage-sdk and worker-store-cs dependencies
* Updated other closed-source dependency (document-message-builder) to open-sourced versions
* **CAF-2245:** Replaced worker-store-cs with worker-store-fs for standard-worker-container
* **CAF-2432:** Removed StorageServiceDataStoreIT and related project from worker-framework as it is no longer used/required

Developer builds are successful and all tests pass

2017-06-12 23:55 UTC, dermot-hardy requested changes
Also, I think we should update the version to 2.0.0, as technically the change to `standard-worker-container` is a breaking change.  We need to list it as a breaking change in the readme.

2017-06-12 23:55 UTC, dermot-hardy commented on worker-archetype/src/main/resources/archetype-resources/__rootArtifactId__-container/pom.xml
> +            <type>pom</type>
Why is the `<type>pom</type>` line changed?  Whitespace change?

2017-06-12 23:55 UTC, dermot-hardy commented on worker-archetype/src/main/resources/archetype-resources/__rootArtifactId__-container/pom.xml
>              <groupId>com.github.workerframework</groupId>
This worker-store-fs dependency should now be removed, since it is coming from `standard-worker-container`.

2017-06-12 23:55 UTC, dermot-hardy commented on worker-example/worker-example-container/pom.xml
>              <groupId>com.github.workerframework</groupId>
This worker-store-fs dependency should now be removed, since it is coming from `standard-worker-container`.

2017-06-12 23:55 UTC, dermot-hardy commented on worker-framework/pom.xml
>          This is present so that the tests are run when the framework is built.
What does this comment now refer to?

2017-06-13 10:10 UTC, arogan92 commented on worker-archetype/src/main/resources/archetype-resources/__rootArtifactId__-container/pom.xml
> +            <type>pom</type>
Yea, some whitespace was added to the end. I will remove it in the next feedback commit

2017-06-13 10:57 UTC, arogan92 commented
Regarding updating the readme 
* Is this a new section on the top-level readme in the repository? Or just put the information within the release-notes?

2017-06-13 11:52 UTC, dermot-hardy commented
Sorry I'm referring to the release notes, not the readme.

2017-06-13 14:41 UTC, arogan92 commented
Versions updated to 2.0.0
Release notes now include "Breaking Changes"

2017-06-13 16:01 UTC, arogan92 commented on worker-archetype/src/main/resources/archetype-resources/__rootArtifactId__-container/pom.xml
> +            <type>pom</type>
Whitespace has been removed

2017-06-13 16:16 UTC, dermot-hardy approved these changes

2017-06-19 12:52 UTC, merged