CAF-2890 Transient failures
WorkerFramework/worker-framework pull request #55
Opened 2017-06-23 12:05 UTC by glucy

A failing health checks will now stop a worker consuming messages from the workers input queue.
Once all health checks pass successfully the worker will resume consuming messages from its input queue

2017-06-23 14:36 UTC, mulhollandc approved these changes

2017-06-23 15:36 UTC, arogan92 reviewed
Just a typo
Code looks good

2017-06-23 15:36 UTC, arogan92 commented on worker-core/src/main/java/com/hpe/caf/worker/core/GatedHealthCheck.java
> +     * worker is disconnecting from it's input queue.
TYPO: disconnected

2017-06-23 15:42 UTC, glucy commented on worker-core/src/main/java/com/hpe/caf/worker/core/GatedHealthCheck.java
> +     * worker is disconnecting from it's input queue.
Already fixed by Connor 👍

2017-06-28 09:45 UTC, glucy commented
@dermot-hardy I've added the additional functionality so works experiencing a transient failure will check health checks before taking on more work.

2017-06-28 10:36 UTC, dermot-hardy requested changes

2017-06-28 10:36 UTC, dermot-hardy commented on worker-core/src/main/java/com/hpe/caf/worker/core/WorkerApplication.java
> +        TransientHealthCheck transientHealthCheck = new TransientHealthCheck();
Extra whitespace at the end of this line.

2017-06-28 10:36 UTC, dermot-hardy commented on worker-core/src/main/java/com/hpe/caf/worker/core/WorkerCore.java
> +        public void abandon(final String queueMsgId, Exception e)
Parameter should be `final`.

2017-06-28 10:36 UTC, dermot-hardy commented on worker-core/src/main/java/com/hpe/caf/worker/core/TransientHealthCheck.java
> +            transientExceptionRegistry.clear();
Thread safety issue here as discussed.

2017-06-28 14:08 UTC, dermot-hardy approved these changes

2017-06-28 14:08 UTC, merged